#!/bin/bash
# This hook is sourced after every virtualenv is activated.

VIRTUAL_ENV_SRC=""
for i in $( cat $VIRTUAL_ENV/lib/python2.7/site-packages/_virtualenv_path_extensions.pth | grep /workspace/ ); do
        VIRTUAL_ENV_SRC="$VIRTUAL_ENV_SRC $i"
done
#VIRTUAL_ENV_SRC="$VIRTUAL_ENV_SRC $VIRTUAL_ENV/lib/python2.7/site-packages/"
echo Processing ctags for following pathes
echo $VIRTUAL_ENV_SRC
git ls-files | grep '\.py$' | ctags -f $VIRTUAL_ENV/tags --tag-relative -R -L - &> /dev/null & disown
#ctags -f $VIRTUAL_ENV/tags -R $VIRTUAL_ENV_SRC 
echo Finished processing ctags
#echo Processing utags
#echo IMPORTANT: Make sure you are at the root folder of the project
#utags -g -n . > $VIRTUAL_ENV/utags
#cp $VIRTUAL_ENV/utags .
#echo Finished processing utags
